"""Whitelist of Volatility 3 plugins exposed through the GUI.

Add new plugins by appending an entry. No other code changes required.
"""

PLUGIN_CONFIG = {
    "banners": {"plugin": "banners.Banners", "label": "Banners", "description": "Attempts to identify potential linux banners in an image", "options": [],},
    "configwriter": {"plugin": "configwriter.ConfigWriter", "label": "ConfigWriter", "description": "Runs the automagics and both prints and outputs configuration in the output directory.", "options": [],},
    "frameworkinfo": {"plugin": "frameworkinfo.FrameworkInfo", "label": "FrameworkInfo", "description": "Plugin to list the various modular components of Volatility", "options": [],},
    "isfinfo": {"plugin": "isfinfo.IsfInfo", "label": "IsfInfo", "description": "Determines information about the currently available ISF files, or a specific one", "options": [],},
    "layerwriter": {"plugin": "layerwriter.LayerWriter", "label": "LayerWriter", "description": "Runs the automagics and writes out the primary layer produced by the stacker.", "options": [],},
    "bash_linux": {"plugin": "linux.bash.Bash", "label": "Bash", "description": "Recovers bash command history from memory.", "options": [],},
    "boottime": {"plugin": "linux.boottime.Boottime", "label": "Boottime", "description": "Shows the time the system was started", "options": [],},
    "capabilities": {"plugin": "linux.capabilities.Capabilities", "label": "Capabilities", "description": "Lists process capabilities", "options": [],},
    "check_afinfo_linux": {"plugin": "linux.check_afinfo.Check_afinfo", "label": "Check_afinfo", "description": "Verifies the operation function pointers of network protocols (deprecated).", "options": [],},
    "check_creds_linux": {"plugin": "linux.check_creds.Check_creds", "label": "Check_creds", "description": "Checks if any processes are sharing credential structures (deprecated).", "options": [],},
    "check_idt_linux": {"plugin": "linux.check_idt.Check_idt", "label": "Check_idt", "description": "Checks if the IDT has been altered (deprecated).", "options": [],},
    "check_modules_linux": {"plugin": "linux.check_modules.Check_modules", "label": "Check_modules", "description": "Compares module list to sysfs info, if available (deprecated).", "options": [],},
    "check_syscall_linux": {"plugin": "linux.check_syscall.Check_syscall", "label": "Check_syscall", "description": "Check system call table for hooks (deprecated).", "options": [],},
    "ebpf": {"plugin": "linux.ebpf.EBPF", "label": "EBPF", "description": "Enumerate eBPF programs", "options": [],},
    "elfs": {"plugin": "linux.elfs.Elfs", "label": "Elfs", "description": "Lists all memory mapped ELF files for all processes.", "options": [],},
    "envars_linux": {"plugin": "linux.envars.Envars", "label": "Envars", "description": "Lists processes with their environment variables", "options": [],},
    "fbdev": {"plugin": "linux.graphics.fbdev.Fbdev", "label": "Fbdev", "description": "Extract framebuffers from the fbdev graphics subsystem", "options": [],},
    "hidden_modules_linux": {"plugin": "linux.hidden_modules.Hidden_modules", "label": "Hidden_modules", "description": "Carves memory to find hidden kernel modules (deprecated).", "options": [],},
    "iomem": {"plugin": "linux.iomem.IOMem", "label": "IOMem", "description": "Generates an output similar to /proc/iomem on a running system.", "options": [],},
    "addr": {"plugin": "linux.ip.Addr", "label": "Addr", "description": "Lists network interface information for all devices", "options": [],},
    "link": {"plugin": "linux.ip.Link", "label": "Link", "description": "Lists information about network interfaces similar to `ip link show`", "options": [],},
    "kallsyms": {"plugin": "linux.kallsyms.Kallsyms", "label": "Kallsyms", "description": "Kallsyms symbols enumeration plugin.", "options": [],},
    "keyboard_notifiers_linux": {"plugin": "linux.keyboard_notifiers.Keyboard_notifiers", "label": "Keyboard_notifiers", "description": "Parses the keyboard notifier call chain (deprecated).", "options": [],},
    "kmsg": {"plugin": "linux.kmsg.Kmsg", "label": "Kmsg", "description": "Kernel log buffer reader", "options": [],},
    "kthreads": {"plugin": "linux.kthreads.Kthreads", "label": "Kthreads", "description": "Enumerates kthread functions", "options": [],},
    "library_list": {"plugin": "linux.library_list.LibraryList", "label": "LibraryList", "description": "Enumerate libraries loaded into processes", "options": [],},
    "lsmod_linux": {"plugin": "linux.lsmod.Lsmod", "label": "Lsmod", "description": "Lists loaded kernel modules.", "options": [],},
    "lsof_linux": {"plugin": "linux.lsof.Lsof", "label": "Lsof", "description": "Lists open files for each processes.", "options": [],},
    "malfind_linux": {"plugin": "linux.malfind.Malfind", "label": "Malfind", "description": "Lists process memory ranges that potentially contain injected code (deprecated).", "options": [],},
    "check_afinfo_linux_malware": {"plugin": "linux.malware.check_afinfo.Check_afinfo", "label": "Check_afinfo", "description": "Verifies the operation function pointers of network protocols.", "options": [],},
    "check_creds_linux_malware": {"plugin": "linux.malware.check_creds.Check_creds", "label": "Check_creds", "description": "Checks if any processes are sharing credential structures", "options": [],},
    "check_idt_linux_malware": {"plugin": "linux.malware.check_idt.Check_idt", "label": "Check_idt", "description": "Checks if the IDT has been altered", "options": [],},
    "check_modules_linux_malware": {"plugin": "linux.malware.check_modules.Check_modules", "label": "Check_modules", "description": "Compares module list to sysfs info, if available", "options": [],},
    "check_syscall_linux_malware": {"plugin": "linux.malware.check_syscall.Check_syscall", "label": "Check_syscall", "description": "Check system call table for hooks.", "options": [],},
    "hidden_modules_linux_malware": {"plugin": "linux.malware.hidden_modules.Hidden_modules", "label": "Hidden_modules", "description": "Carves memory to find hidden kernel modules", "options": [],},
    "keyboard_notifiers_linux_malware": {"plugin": "linux.malware.keyboard_notifiers.Keyboard_notifiers", "label": "Keyboard_notifiers", "description": "Parses the keyboard notifier call chain", "options": [],},
    "malfind_linux_malware": {"plugin": "linux.malware.malfind.Malfind", "label": "Malfind", "description": "Lists process memory ranges that potentially contain injected code.", "options": [],},
    "modxview_linux_malware": {"plugin": "linux.malware.modxview.Modxview", "label": "Modxview", "description": "Centralize lsmod, check_modules and hidden_modules results to efficiently spot modules presence and taints.", "options": [],},
    "netfilter_linux_malware": {"plugin": "linux.malware.netfilter.Netfilter", "label": "Netfilter", "description": "Lists Netfilter hooks.", "options": [],},
    "process_spoofing": {"plugin": "linux.malware.process_spoofing.ProcessSpoofing", "label": "ProcessSpoofing", "description": "Detects process spoofing by comparing executable path to cmdline & comm fields.", "options": [],},
    "tty_check_linux_malware": {"plugin": "linux.malware.tty_check.Tty_Check", "label": "Tty_Check", "description": "Checks tty devices for hooks", "options": [],},
    "module_extract": {"plugin": "linux.module_extract.ModuleExtract", "label": "ModuleExtract", "description": "Recreates an ELF file from a specific address in the kernel", "options": [],},
    "modxview_linux": {"plugin": "linux.modxview.Modxview", "label": "Modxview", "description": "Centralize lsmod, check_modules and hidden_modules results to efficiently spot modules presence and taints (deprecated).", "options": [],},
    "mountinfo": {"plugin": "linux.mountinfo.MountInfo", "label": "MountInfo", "description": "Lists mount points on processes mount namespaces", "options": [],},
    "netfilter_linux": {"plugin": "linux.netfilter.Netfilter", "label": "Netfilter", "description": "Lists Netfilter hooks (deprecated).", "options": [],},
    "files": {"plugin": "linux.pagecache.Files", "label": "Files", "description": "Lists files from memory", "options": [],},
    "inodepages": {"plugin": "linux.pagecache.InodePages", "label": "InodePages", "description": "Lists and recovers cached inode pages", "options": [],},
    "recoverfs": {"plugin": "linux.pagecache.RecoverFs", "label": "RecoverFs", "description": "Recovers the cached filesystem (directories, files, symlinks) into a compressed tarball.", "options": [],},
    "pidhashtable": {"plugin": "linux.pidhashtable.PIDHashTable", "label": "PIDHashTable", "description": "Enumerates processes through the PID hash table", "options": [],},
    "maps_linux": {"plugin": "linux.proc.Maps", "label": "Maps", "description": "Lists all memory maps for all processes.", "options": [],},
    "psaux_linux": {"plugin": "linux.psaux.PsAux", "label": "PsAux", "description": "Lists processes with their command line arguments", "options": [],},
    "pscallstack": {"plugin": "linux.pscallstack.PsCallStack", "label": "PsCallStack", "description": "Enumerates the call stack of each task", "options": [],},
    "pslist_linux": {"plugin": "linux.pslist.PsList", "label": "PsList", "description": "Lists the processes present in a particular linux memory image.", "options": [],},
    "psscan_linux": {"plugin": "linux.psscan.PsScan", "label": "PsScan", "description": "Scans for processes present in a particular linux image.", "options": [],},
    "pstree_linux": {"plugin": "linux.pstree.PsTree", "label": "PsTree", "description": "Plugin for listing processes in a tree based on their parent process ID.", "options": [],},
    "ptrace": {"plugin": "linux.ptrace.Ptrace", "label": "Ptrace", "description": "Enumerates ptrace's tracer and tracee tasks", "options": [],},
    "sockscan": {"plugin": "linux.sockscan.Sockscan", "label": "Sockscan", "description": "Scans for network connections found in memory layer.", "options": [],},
    "sockstat": {"plugin": "linux.sockstat.Sockstat", "label": "Sockstat", "description": "Lists all network connections for all processes.", "options": [],},
    "checkftrace": {"plugin": "linux.tracing.ftrace.CheckFtrace", "label": "CheckFtrace", "description": "Detect ftrace hooking", "options": [],},
    "perfevents": {"plugin": "linux.tracing.perf_events.PerfEvents", "label": "PerfEvents", "description": "Lists performance events for each process.", "options": [],},
    "checktracepoints": {"plugin": "linux.tracing.tracepoints.CheckTracepoints", "label": "CheckTracepoints", "description": "Detect tracepoints hooking", "options": [],},
    "tty_check_linux": {"plugin": "linux.tty_check.tty_check", "label": "tty_check", "description": "Checks tty devices for hooks (deprecated).", "options": [],},
    "vmaregexscan": {"plugin": "linux.vmaregexscan.VmaRegExScan", "label": "VmaRegExScan", "description": "Scans all virtual memory areas for tasks using RegEx.", "options": [],},
    "vmcoreinfo": {"plugin": "linux.vmcoreinfo.VMCoreInfo", "label": "VMCoreInfo", "description": "Enumerate VMCoreInfo tables", "options": [],},
    "bash_mac": {"plugin": "mac.bash.Bash", "label": "Bash", "description": "Recovers bash command history from memory.", "options": [],},
    "check_syscall_mac": {"plugin": "mac.check_syscall.Check_syscall", "label": "Check_syscall", "description": "Check system call table for hooks.", "options": [],},
    "check_sysctl": {"plugin": "mac.check_sysctl.Check_sysctl", "label": "Check_sysctl", "description": "Check sysctl handlers for hooks.", "options": [],},
    "check_trap_table": {"plugin": "mac.check_trap_table.Check_trap_table", "label": "Check_trap_table", "description": "Check mach trap table for hooks.", "options": [],},
    "dmesg": {"plugin": "mac.dmesg.Dmesg", "label": "Dmesg", "description": "Prints the kernel log buffer.", "options": [],},
    "ifconfig": {"plugin": "mac.ifconfig.Ifconfig", "label": "Ifconfig", "description": "Lists network interface information for all devices", "options": [],},
    "kauth_listeners": {"plugin": "mac.kauth_listeners.Kauth_listeners", "label": "Kauth_listeners", "description": "Lists kauth listeners and their status", "options": [],},
    "kauth_scopes": {"plugin": "mac.kauth_scopes.Kauth_scopes", "label": "Kauth_scopes", "description": "Lists kauth scopes and their status", "options": [],},
    "kevents": {"plugin": "mac.kevents.Kevents", "label": "Kevents", "description": "Lists event handlers registered by processes", "options": [],},
    "list_files": {"plugin": "mac.list_files.List_Files", "label": "List_Files", "description": "Lists all open file descriptors for all processes.", "options": [],},
    "lsmod_mac": {"plugin": "mac.lsmod.Lsmod", "label": "Lsmod", "description": "Lists loaded kernel modules.", "options": [],},
    "lsof_mac": {"plugin": "mac.lsof.Lsof", "label": "Lsof", "description": "Lists all open file descriptors for all processes.", "options": [],},
    "malfind_mac": {"plugin": "mac.malfind.Malfind", "label": "Malfind", "description": "Lists process memory ranges that potentially contain injected code.", "options": [],},
    "mount": {"plugin": "mac.mount.Mount", "label": "Mount", "description": "A module containing a collection of plugins that produce data typically found in Mac's mount command", "options": [],},
    "netstat_mac": {"plugin": "mac.netstat.Netstat", "label": "Netstat", "description": "Lists all network connections for all processes.", "options": [],},
    "maps_mac": {"plugin": "mac.proc_maps.Maps", "label": "Maps", "description": "Lists process memory ranges that potentially contain injected code.", "options": [],},
    "psaux_mac": {"plugin": "mac.psaux.Psaux", "label": "Psaux", "description": "Recovers program command line arguments.", "options": [],},
    "pslist_mac": {"plugin": "mac.pslist.PsList", "label": "PsList", "description": "Lists the processes present in a particular mac memory image.", "options": [],},
    "pstree_mac": {"plugin": "mac.pstree.PsTree", "label": "PsTree", "description": "Plugin for listing processes in a tree based on their parent process ID.", "options": [],},
    "socket_filters": {"plugin": "mac.socket_filters.Socket_filters", "label": "Socket_filters", "description": "Enumerates kernel socket filters.", "options": [],},
    "timers_mac": {"plugin": "mac.timers.Timers", "label": "Timers", "description": "Check for malicious kernel timers.", "options": [],},
    "trustedbsd": {"plugin": "mac.trustedbsd.Trustedbsd", "label": "Trustedbsd", "description": "Checks for malicious trustedbsd modules", "options": [],},
    "vfsevents": {"plugin": "mac.vfsevents.VFSevents", "label": "VFSevents", "description": "Lists processes that are filtering file system events", "options": [],},
    "regexscan": {"plugin": "regexscan.RegExScan", "label": "RegExScan", "description": "Scans kernel memory using RegEx patterns.", "options": [],},
    "timeliner": {"plugin": "timeliner.Timeliner", "label": "Timeliner", "description": "Runs all relevant plugins that provide time related information and orders the results by time.", "options": [],},
    "vmscan": {"plugin": "vmscan.Vmscan", "label": "Vmscan", "description": "Scans for Intel VT-d structures and generates VM volatility configs for them", "options": [],},
    "amcache_windows": {"plugin": "windows.amcache.Amcache", "label": "Amcache", "description": "Extract information on executed applications from the AmCache (deprecated).", "options": [],},
    "bigpools": {"plugin": "windows.bigpools.BigPools", "label": "BigPools", "description": "List big page pools.", "options": [],},
    "callbacks": {"plugin": "windows.callbacks.Callbacks", "label": "Callbacks", "description": "Lists kernel callbacks and notification routines.", "options": [],},
    "cmdline": {"plugin": "windows.cmdline.CmdLine", "label": "CmdLine", "description": "Lists process command line arguments.", "options": [],},
    "cmdscan": {"plugin": "windows.cmdscan.CmdScan", "label": "CmdScan", "description": "Looks for Windows Command History lists", "options": [],},
    "consoles": {"plugin": "windows.consoles.Consoles", "label": "Consoles", "description": "Looks for Windows console buffers", "options": [],},
    "crashinfo": {"plugin": "windows.crashinfo.Crashinfo", "label": "Crashinfo", "description": "Lists the information from a Windows crash dump.", "options": [],},
    "debugregisters": {"plugin": "windows.debugregisters.DebugRegisters", "label": "DebugRegisters", "description": "", "options": [],},
    "deskscan": {"plugin": "windows.deskscan.DeskScan", "label": "DeskScan", "description": "Scans for the Desktop instances of each Window Station", "options": [],},
    "desktops": {"plugin": "windows.desktops.Desktops", "label": "Desktops", "description": "Enumerates the Desktop instances of each Window Station", "options": [],},
    "devicetree": {"plugin": "windows.devicetree.DeviceTree", "label": "DeviceTree", "description": "Listing tree based on drivers and attached devices in a particular windows memory image.", "options": [],},
    "dlllist": {"plugin": "windows.dlllist.DllList", "label": "DllList", "description": "Lists the loaded DLLs in a particular windows memory image.", "options": [],},
    "driverirp": {"plugin": "windows.driverirp.DriverIrp", "label": "DriverIrp", "description": "List IRPs for drivers in a particular windows memory image.", "options": [],},
    "drivermodule_windows": {"plugin": "windows.drivermodule.DriverModule", "label": "DriverModule", "description": "Determines if any loaded drivers were hidden by a rootkit (deprecated).", "options": [],},
    "driverscan": {"plugin": "windows.driverscan.DriverScan", "label": "DriverScan", "description": "Scans for drivers present in a particular windows memory image.", "options": [],},
    "dumpfiles": {"plugin": "windows.dumpfiles.DumpFiles", "label": "DumpFiles", "description": "Dumps cached file contents from Windows memory samples.", "options": [],},
    "envars_windows": {"plugin": "windows.envars.Envars", "label": "Envars", "description": "Display process environment variables", "options": [],},
    "etwpatch": {"plugin": "windows.etwpatch.EtwPatch", "label": "EtwPatch", "description": "Identifies ETW (Event Tracing for Windows) patching techniques used by malware to evade detection.", "options": [],},
    "filescan": {"plugin": "windows.filescan.FileScan", "label": "FileScan", "description": "Scans for file objects present in a particular windows memory image.", "options": [],},
    "getservicesids": {"plugin": "windows.getservicesids.GetServiceSIDs", "label": "GetServiceSIDs", "description": "Lists process token sids.", "options": [],},
    "getsids": {"plugin": "windows.getsids.GetSIDs", "label": "GetSIDs", "description": "Print the SIDs owning each process", "options": [],},
    "handles": {"plugin": "windows.handles.Handles", "label": "Handles", "description": "Lists process open handles.", "options": [],},
    "hollowprocesses_windows": {"plugin": "windows.hollowprocesses.HollowProcesses", "label": "HollowProcesses", "description": "Lists hollowed processes (deprecated)", "options": [],},
    "iat": {"plugin": "windows.iat.IAT", "label": "IAT", "description": "Extract Import Address Table to list API (functions) used by a program contained in external libraries", "options": [],},
    "info": {"plugin": "windows.info.Info", "label": "Info", "description": "Show OS & kernel details of the memory sample being analyzed.", "options": [],},
    "joblinks": {"plugin": "windows.joblinks.JobLinks", "label": "JobLinks", "description": "Print process job link information", "options": [],},
    "kpcrs": {"plugin": "windows.kpcrs.KPCRs", "label": "KPCRs", "description": "Print KPCR structure for each processor", "options": [],},
    "ldrmodules_windows": {"plugin": "windows.ldrmodules.LdrModules", "label": "LdrModules", "description": "Lists the loaded modules in a particular windows memory image.", "options": [],},
    "malfind_windows": {"plugin": "windows.malfind.Malfind", "label": "Malfind", "description": "Lists process memory ranges that potentially contain injected code (deprecated).", "options": [],},
    "drivermodule_windows_malware": {"plugin": "windows.malware.drivermodule.DriverModule", "label": "DriverModule", "description": "Determines if any loaded drivers were hidden by a rootkit", "options": [],},
    "hollowprocesses_windows_malware": {"plugin": "windows.malware.hollowprocesses.HollowProcesses", "label": "HollowProcesses", "description": "Lists hollowed processes", "options": [],},
    "ldrmodules_windows_malware": {"plugin": "windows.malware.ldrmodules.LdrModules", "label": "LdrModules", "description": "Lists the loaded modules in a particular windows memory image.", "options": [],},
    "malfind_windows_malware": {"plugin": "windows.malware.malfind.Malfind", "label": "Malfind", "description": "Lists process memory ranges that potentially contain injected code.", "options": [],},
    "pebmasquerade": {"plugin": "windows.malware.pebmasquerade.PebMasquerade", "label": "PebMasquerade", "description": "Detects potential process name spoofing by comparing EPROCESS and PEB data.", "options": [],},
    "processghosting_windows_malware": {"plugin": "windows.malware.processghosting.ProcessGhosting", "label": "ProcessGhosting", "description": "Lists processes whose DeletePending bit is set or whose FILE_OBJECT is set to 0 or Vads that are DeleteOnClose", "options": [],},
    "psxview_windows_malware": {"plugin": "windows.malware.psxview.PsXView", "label": "PsXView", "description": "Lists all processes found via four of the methods described in \"The Art of Memory Forensics\" which may help identify processes that are trying to hide themselves.", "options": [],},
    "skeleton_key_check_windows_malware": {"plugin": "windows.malware.skeleton_key_check.Skeleton_Key_Check", "label": "Skeleton_Key_Check", "description": "Looks for signs of Skeleton Key malware", "options": [],},
    "suspicious_threads_windows_malware": {"plugin": "windows.malware.suspicious_threads.SuspiciousThreads", "label": "SuspiciousThreads", "description": "Lists suspicious userland process threads", "options": [],},
    "svcdiff_windows_malware": {"plugin": "windows.malware.svcdiff.SvcDiff", "label": "SvcDiff", "description": "Compares services found through list walking versus scanning to find rootkits", "options": [],},
    "unhooked_system_calls_windows_malware": {"plugin": "windows.malware.unhooked_system_calls.UnhookedSystemCalls", "label": "UnhookedSystemCalls", "description": "Detects hooked ntdll.dll stub functions in Windows processes.", "options": [],},
    "mbrscan": {"plugin": "windows.mbrscan.MBRScan", "label": "MBRScan", "description": "Scans for and parses potential Master Boot Records (MBRs)", "options": [],},
    "memmap": {"plugin": "windows.memmap.Memmap", "label": "Memmap", "description": "Prints the memory map", "options": [],},
    "modscan": {"plugin": "windows.modscan.ModScan", "label": "ModScan", "description": "Scans for modules present in a particular windows memory image.", "options": [],},
    "modules": {"plugin": "windows.modules.Modules", "label": "Modules", "description": "Lists the loaded kernel modules.", "options": [],},
    "mutantscan": {"plugin": "windows.mutantscan.MutantScan", "label": "MutantScan", "description": "Scans for mutexes present in a particular windows memory image.", "options": [],},
    "netscan": {"plugin": "windows.netscan.NetScan", "label": "NetScan", "description": "Scans for network objects present in a particular windows memory image.", "options": [],},
    "netstat_windows": {"plugin": "windows.netstat.NetStat", "label": "NetStat", "description": "Traverses network tracking structures present in a particular windows memory image.", "options": [],},
    "threads_orphan_windows": {"plugin": "windows.orphan_kernel_threads.Threads", "label": "Threads", "description": "Lists process threads", "options": [],},
    "pe_symbols": {"plugin": "windows.pe_symbols.PESymbols", "label": "PESymbols", "description": "Prints symbols in PE files in process and kernel memory", "options": [],},
    "pedump": {"plugin": "windows.pedump.PEDump", "label": "PEDump", "description": "Allows extracting PE Files from a specific address in a specific address space", "options": [],},
    "poolscanner": {"plugin": "windows.poolscanner.PoolScanner", "label": "PoolScanner", "description": "A generic pool scanner plugin.", "options": [],},
    "privs": {"plugin": "windows.privileges.Privs", "label": "Privs", "description": "Lists process token privileges", "options": [],},
    "processghosting_windows": {"plugin": "windows.processghosting.ProcessGhosting", "label": "ProcessGhosting", "description": "Lists processes whose DeletePending bit is set or whose FILE_OBJECT is set to 0 or Vads that are DeleteOnClose (deprecated).", "options": [],},
    "pslist_windows": {"plugin": "windows.pslist.PsList", "label": "PsList", "description": "Lists the processes present in a particular windows memory image.", "options": [],},
    "psscan_windows": {"plugin": "windows.psscan.PsScan", "label": "PsScan", "description": "Scans for processes present in a particular windows memory image.", "options": [],},
    "pstree_windows": {"plugin": "windows.pstree.PsTree", "label": "PsTree", "description": "Plugin for listing processes in a tree based on their parent process ID.", "options": [],},
    "psxview_windows": {"plugin": "windows.psxview.PsXView", "label": "PsXView", "description": "Lists all processes found via four of the methods described in \"The Art of Memory Forensics\" which may help identify processes that are trying to hide themselves.", "options": [],},
    "amcache_windows_registry": {"plugin": "windows.registry.amcache.Amcache", "label": "Amcache", "description": "Extract information on executed applications from the AmCache.", "options": [],},
    "certificates": {"plugin": "windows.registry.certificates.Certificates", "label": "Certificates", "description": "Lists the certificates in the registry's Certificate Store.", "options": [],},
    "getcellroutine": {"plugin": "windows.registry.getcellroutine.GetCellRoutine", "label": "GetCellRoutine", "description": "Reports registry hives with a hooked GetCellRoutine handler", "options": [],},
    "hivelist": {"plugin": "windows.registry.hivelist.HiveList", "label": "HiveList", "description": "Lists the registry hives present in a particular memory image.", "options": [],},
    "hivescan": {"plugin": "windows.registry.hivescan.HiveScan", "label": "HiveScan", "description": "Scans for registry hives present in a particular windows memory image.", "options": [],},
    "printkey": {"plugin": "windows.registry.printkey.PrintKey", "label": "PrintKey", "description": "Lists the registry keys under a hive or specific key value.", "options": [],},
    "scheduled_tasks_windows_registry": {"plugin": "windows.registry.scheduled_tasks.ScheduledTasks", "label": "ScheduledTasks", "description": "Decodes scheduled task information from the Windows registry, including information about triggers, actions, run times, and creation times.", "options": [],},
    "userassist": {"plugin": "windows.registry.userassist.UserAssist", "label": "UserAssist", "description": "Print userassist registry keys and information.", "options": [],},
    "scheduled_tasks_windows": {"plugin": "windows.scheduled_tasks.ScheduledTasks", "label": "ScheduledTasks", "description": "Decodes scheduled task information from the Windows registry, including information about triggers, actions, run times, and creation times (deprecated).", "options": [],},
    "sessions": {"plugin": "windows.sessions.Sessions", "label": "Sessions", "description": "lists Processes with Session information extracted from Environmental Variables", "options": [],},
    "shimcachemem": {"plugin": "windows.shimcachemem.ShimcacheMem", "label": "ShimcacheMem", "description": "Reads Shimcache entries from the ahcache.sys AVL tree", "options": [],},
    "skeleton_key_check_windows": {"plugin": "windows.skeleton_key_check.Skeleton_Key_Check", "label": "Skeleton_Key_Check", "description": "Looks for signs of Skeleton Key malware", "options": [],},
    "ssdt": {"plugin": "windows.ssdt.SSDT", "label": "SSDT", "description": "Lists the system call table.", "options": [],},
    "statistics": {"plugin": "windows.statistics.Statistics", "label": "Statistics", "description": "Lists statistics about the memory space.", "options": [],},
    "strings": {"plugin": "windows.strings.Strings", "label": "Strings", "description": "Reads output from the strings command and indicates which process(es) each string belongs to.", "options": [],},
    "suspended_threads": {"plugin": "windows.suspended_threads.SuspendedThreads", "label": "SuspendedThreads", "description": "Enumerates suspended threads.", "options": [],},
    "suspicious_threads_windows": {"plugin": "windows.suspicious_threads.SuspiciousThreads", "label": "SuspiciousThreads", "description": "Lists suspicious userland process threads (deprecated).", "options": [],},
    "svcdiff_windows": {"plugin": "windows.svcdiff.SvcDiff", "label": "SvcDiff", "description": "Compares services found through list walking versus scanning to find rootkits (deprecated).", "options": [],},
    "svclist": {"plugin": "windows.svclist.SvcList", "label": "SvcList", "description": "Lists services contained with the services.exe doubly linked list of services", "options": [],},
    "svcscan": {"plugin": "windows.svcscan.SvcScan", "label": "SvcScan", "description": "Scans for windows services.", "options": [],},
    "symlinkscan": {"plugin": "windows.symlinkscan.SymlinkScan", "label": "SymlinkScan", "description": "Scans for links present in a particular windows memory image.", "options": [],},
    "thrdscan": {"plugin": "windows.thrdscan.ThrdScan", "label": "ThrdScan", "description": "Scans for windows threads.", "options": [],},
    "threads_windows": {"plugin": "windows.threads.Threads", "label": "Threads", "description": "Lists process threads", "options": [],},
    "timers_windows": {"plugin": "windows.timers.Timers", "label": "Timers", "description": "Print kernel timers and associated module DPCs", "options": [],},
    "passphrase": {"plugin": "windows.truecrypt.Passphrase", "label": "Passphrase", "description": "TrueCrypt Cached Passphrase Finder", "options": [],},
    "unhooked_system_calls_windows": {"plugin": "windows.unhooked_system_calls.unhooked_system_calls", "label": "unhooked_system_calls", "description": "Detects hooked ntdll.dll stub functions in Windows processes (deprecated).", "options": [],},
    "unloadedmodules": {"plugin": "windows.unloadedmodules.UnloadedModules", "label": "UnloadedModules", "description": "Lists the unloaded kernel modules.", "options": [],},
    "vadinfo": {"plugin": "windows.vadinfo.VadInfo", "label": "VadInfo", "description": "Lists process memory ranges.", "options": [],},
    "vadregexscan": {"plugin": "windows.vadregexscan.VadRegExScan", "label": "VadRegExScan", "description": "Scans all virtual memory areas for tasks using RegEx.", "options": [],},
    "vadwalk": {"plugin": "windows.vadwalk.VadWalk", "label": "VadWalk", "description": "Walk the VAD tree.", "options": [],},
    "verinfo": {"plugin": "windows.verinfo.VerInfo", "label": "VerInfo", "description": "Lists version information from PE files.", "options": [],},
    "virtmap": {"plugin": "windows.virtmap.VirtMap", "label": "VirtMap", "description": "Lists virtual mapped sections.", "options": [],},
    "windows": {"plugin": "windows.windows.Windows", "label": "Windows", "description": "Enumerates the Windows of Desktop instances", "options": [],},
    "windowstations": {"plugin": "windows.windowstations.WindowStations", "label": "WindowStations", "description": "Scans for top level Windows Stations", "options": [],},
}

def get_plugin(name: str) -> dict:
    if name not in PLUGIN_CONFIG:
        raise ValueError(f"Unknown plugin '{name}'.")
    return PLUGIN_CONFIG[name]


def list_plugins() -> list[dict]:
    return [{"id": k, **v} for k, v in PLUGIN_CONFIG.items()]